Fix Message::parseRequestUri() for numeric headers
guzzle/psr7 pull request #503
Opened 2022-04-27 13:46 UTC by TimWolla

Fixes guzzle/psr7#497

2022-04-27 17:30 UTC, GrahamCampbell requested changes

2022-04-27 17:32 UTC, TimWolla commented on src/Message.php
> +                // Numeric array keys are converted to int by PHP but having a header name '123' is not forbidden by the spec.
I've stolen this from `MessageTrait::setHeaders()`:

https://github.com/guzzle/psr7/blob/8f199b15f06c5b2b101aa87a073f652fca506ba0/src/MessageTrait.php#L148-L152

I can adjust both locations if that's what you prefer?

2022-04-28 17:44 UTC, GrahamCampbell approved these changes

2022-04-28 17:45 UTC, merged

2022-04-28 17:45 UTC, GrahamCampbell commented
🍻